# -*- coding: utf-8 -*-
"""Mask RCNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TTcMjPfxGSsGiwIZ3OfdLrnNif1pnBuq
"""

!pip install --upgrade --force-reinstall --no-deps kaggle

# Commented out IPython magic to ensure Python compatibility.
#from google.colab import drive
#drive.mount('/content/gdrive')
import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/My Drive/Kaggle"
# /content/gdrive/My Drive/Kaggle is the path where kaggle.json is present in the Google Drive
#changing the working directory
# %cd /content/gdrive/My Drive/Kaggle
#Check the present working directory using pwd command
!kaggle competitions download -c severstal-steel-defect-detection
!ls

#unzipping the zip files and deleting the zip files
!unzip \*.zip

!ls